baseURL: https://katarinaore.netlify.app/
languageCode: en-us
title: Portfolio Website for Katerina Vasileva
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
    #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #  AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Kate
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kvasileva.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (0) 7788-7868 1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Katarina Ore Inc.
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/katarinaore/
      - icon: fa-github
        label: GitHub
        url: https://github.com/katarinaore
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/katerinavasileva08/
  image: ''
  name: Katerina Vasileva
  navigation:
    button1:
      - name: Get Started
        url: blogs
   # button2:
   #   - name: Log In
   #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
     # - name: Generic Blog
     #   url: blogs/ipsum
     # - name: Elements
     #   url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
   # title: Forty
  tiles:
    enable: yes
    showcase:
      - image: tile1.jpg
        subtitle: Background, education, experiences
        title: About me
        url: blogs/about
      - image: aspire.jpeg
        subtitle: Things that interest and inspire me
        title: Aspirations
        url: blogs/aspire
      - image: tile3.jpg
        subtitle: Analysis on Airbnb prices in Rio De Janeiro 
        title: Airbnb Prices Analysis
        url: blogs/Airbnb
      - image: tile4.jpg
        subtitle: Analysis of the temperature anomalies in the Northern Hemisphere
        title: Climate Change Analysis
        url: blogs/climate
      #- image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
      #  title: Consequat
      #  url: blogs/ipsum
      #- image: pic06.jpg
      #  subtitle: Feugiat Amet Tempus
      #  title: Etiam
      #  url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
    # title: Massa libero
    url: blogs
